name: Application OIDC

on:
  push:
    branches: [ main ]
    paths: ['karavan-app/**', 'karavan-core/**', 'karavan-designer/**', '.github/workflows/app.yml']
  workflow_dispatch:
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  TAG: 4.14.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Karavan
        uses: actions/checkout@v5
        with:
          path: karavan

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/apache/camel/karavan
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Karavan Core install
        working-directory: ./karavan/karavan-core
        run: npm ci

      - name: Build and Push OIDC application with Jib
        working-directory: ./karavan/karavan-app
        run: |
          mvn package -Dquarkus.profile=oidc -DskipTests \
          -Dquarkus.quinoa.package-manager-install=false \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=${{ github.event_name != 'pull_request' }} \
          -Dquarkus.jib.platforms=linux/amd64,linux/arm64 \
          -Dquarkus.container-image.registry=${{ env.REGISTRY }} \
          -Dquarkus.container-image.name=${GITHUB_REPOSITORY} \
          -Dquarkus.container-image.tag=${{ env.TAG }}-oidc \
          -Dquarkus.container-image.group= \
          -Dquarkus.container-image.username=${{ github.actor }} \
          -Dquarkus.container-image.password=${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.ref == 'refs/heads/main' }}
